// src/app/donate/page.tsx
export default function Donate() {
  return (
    <div className="max-w-3xl mx-auto text-center">
      <h1 className="text-4xl font-semibold">Donate</h1>
      <p className="text-lg font-semibold pt-2">
        I appreciate any donations of any amount!
      </p>
      <div className="flex flex-col items-center pt-3">
        <a
          href="https://ko-fi.com/Z8Z810D8H7"
          rel="noopener noreferrer"
          target="_blank"
        >
          {/*eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="mx-auto"
            src="/ko-fi_donate.svg"
            alt="Support me on Ko-fi"
          />
        </a>
      </div>
      <div className="flex justify-center items-center pt-3 pb-3">
        <p className="text-lg">
          PayPal:{" "}
          <a
            className="text-blue-500"
            href="https://www.paypal.com/paypalme/codingjosh"
            rel="noopener noreferrer"
            target="_blank"
          >
            @codingjosh
          </a>
        </p>
      </div>
      <p className="text-sm">Thank you for even considering donating!</p>
    </div>
  );
}

// pages/donate.vue
<template>
  <div class="max-w-3xl mx-auto text-center">
    <h1 class="text-4xl font-semibold">Donate</h1>
    <p class="text-lg font-semibold pt-2">I appreciate any donations of any amount!</p>
    <div class="flex flex-col items-center pt-3">
      <a href="https://ko-fi.com/Z8Z810D8H7" target="_blank">
        <img class="mx-auto" src="assets/images/ko-fi_donate.svg" alt="Support me on Ko-fi" />
      </a>
    </div>
    <div class="flex justify-center items-center pt-3 pb-3">
      <p class="text-lg">PayPal: <a class="text-blue-500" href="https://www.paypal.com/paypalme/codingjosh"
          target="_blank">@codingjosh</a></p>
    </div>
    <p class="text-sm">Thank you for even considering donating!</p>
  </div>
</template>

<script lang="ts" setup>

</script>

<style></style>
